spring:
  config:
    import: application_secret.yml
  application:
    name: telegram_part

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
      database: postgresql

  datasource:
    url: jdbc:postgresql://localhost:5432/pattern_bot_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: 8083

telegram:
  bot:
    name: ${TG_NAME}
    token: ${TG_TOKEN}